pipeline {
   agent any

   stages {
      stage('Checkout') {
         steps {
            git url: 'https://github.com/zepedrorodrigues/devops-23-24-JPE-PSM-1231837.git', branch: 'master'
         }
      }
      stage('Create Dockerfile') {
         steps {
            dir('CA2/Part2/demo') {
               echo 'Creating Dockerfile...'
               script {
                  writeFile file: 'Dockerfile', text: '''
                        # Use the official OpenJDK image as a parent image
                        FROM openjdk:17-jdk-alpine

                        # Set the working directory in the container
                        WORKDIR /app

                        # Copy the JAR file from the host to the container
                        COPY build/libs/*.jar app.jar

                        # Expose the port that the application will run on
                        EXPOSE 8080

                        # Run the JAR file
                        ENTRYPOINT ["java", "-jar", "app.jar"]
                        '''
               }
            }
         }
      }
      stage('Assemble') {
         steps {
            dir('CA2/Part2/demo') {
               sh 'chmod +x ./gradlew'
               sh './gradlew assemble'
            }
         }
      }
      stage('List Build Directory') {
                  steps {
                      dir('CA2/Part2/demo') {
                          echo 'Listing build directory contents...'
                          sh 'ls -l build'
                          echo 'Listing libs directory contents...'
                          sh 'ls -l build/libs'
                      }
                  }
              }
      stage('Verify Build') {
                  steps {
                      dir('CA2/Part2/demo/build/libs') {
                          script {
                              if (!fileExists('*.jar')) {
                                  error 'JAR file not found!'
                              }
                          }
                      }
                  }
              }
      stage('Test') {
         steps {
            dir('CA2/Part2/demo') {
               sh 'chmod +x ./gradlew'
               sh './gradlew test'
            }
            junit '**/build/test-results/test/*.xml'
         }
      }
      stage('Javadoc') {
         steps {
            dir('CA2/Part2/demo') {
               sh './gradlew javadoc'
               publishHTML(target: [
                       reportDir: 'build/docs/javadoc',
                       reportFiles: 'index.html',
                       reportName: 'Javadoc',
                       keepAll: true,
                       alwaysLinkToLastBuild: true,
                       allowMissing: false
               ])
            }
         }
      }
      stage('Archive') {
         steps {
            archiveArtifacts artifacts: 'CA2/Part2/demo/build/libs/*.jar', allowEmptyArchive: true
         }
      }
      stage('PublishImage') {
         steps {
            dir('CA2/Part2/demo') {
            script {
               echo 'Building Docker Image...'
               sh 'docker info'
               def app = docker.build("${env.DOCKER_IMAGE}:${env.BUILD_ID}", '.')
               docker.withRegistry(env.DOCKER_REGISTRY, env.DOCKER_CREDENTIALS_ID) {
                  app.push()
               }
            }
         }
      }
   }}
}